version: '3.8'

services:
  php:
    image: php:8.2-apache
    container_name: php82
    ports:
      - 8000:80
    volumes:
      - ./php:/var/www/html
    build:
      context: .
      dockerfile: DockerFile
  db: 
    image: mysql:8.1
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: demo
      MYSQL_USER: test
      MYSQL_PASSWORD: pass
    ports:
      - 3307:3306

